//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_LTW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAIMON
    {
        public LOAIMON()
        {
            this.MONANs = new HashSet<MONAN>();
        }
    
        public string MaLoai { get; set; }
        public string TenLoai { get; set; }
    
        public virtual ICollection<MONAN> MONANs { get; set; }
    }
}
