//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_LTW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHATKY_DANGNHAP
    {
        public int ID { get; set; }
        public string TenDangNhap { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public string DiaChiIP { get; set; }
    }
}
