//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_LTW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAIKHOAN
    {
        public TAIKHOAN()
        {
            this.NHATKY_PHANQUYEN = new HashSet<NHATKY_PHANQUYEN>();
            this.NHATKY_PHANQUYEN1 = new HashSet<NHATKY_PHANQUYEN>();
        }
    
        public string TenDangNhap { get; set; }
        public string MatKhau { get; set; }
        public string MaNV { get; set; }
        public string MaKH { get; set; }
        public string Quyen { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual ICollection<NHATKY_PHANQUYEN> NHATKY_PHANQUYEN { get; set; }
        public virtual ICollection<NHATKY_PHANQUYEN> NHATKY_PHANQUYEN1 { get; set; }
    }
}
