//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_LTW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATBAN
    {
        public DATBAN()
        {
            this.HOADONs = new HashSet<HOADON>();
        }
    
        public string MaDatBan { get; set; }
        public string MaKH { get; set; }
        public string MaBan { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public System.TimeSpan GioDat { get; set; }
        public string TrangThai { get; set; }
    
        public virtual BANAN BANAN { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual ICollection<HOADON> HOADONs { get; set; }
    }
}
