//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_LTW.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QL_NHAHANGEntities : DbContext
    {
        public QL_NHAHANGEntities()
            : base("name=QL_NHAHANGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BANAN> BANANs { get; set; }
        public DbSet<CHITIETHOADON> CHITIETHOADONs { get; set; }
        public DbSet<DATBAN> DATBANs { get; set; }
        public DbSet<HOADON> HOADONs { get; set; }
        public DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public DbSet<LOAIMON> LOAIMONs { get; set; }
        public DbSet<MONAN> MONANs { get; set; }
        public DbSet<NHANVIEN> NHANVIENs { get; set; }
        public DbSet<TAIKHOAN> TAIKHOANs { get; set; }
        public DbSet<CHITIET_NHAPKHO> CHITIET_NHAPKHO { get; set; }
        public DbSet<MONAN_NGUYENLIEU> MONAN_NGUYENLIEU { get; set; }
        public DbSet<NGUYENLIEU> NGUYENLIEUx { get; set; }
        public DbSet<NHATKY_DANGNHAP> NHATKY_DANGNHAP { get; set; }
        public DbSet<NHATKY_PHANQUYEN> NHATKY_PHANQUYEN { get; set; }
        public DbSet<PHIEUNHAPKHO> PHIEUNHAPKHOes { get; set; }
    }
}
