//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_LTW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACHHANG
    {
        public KHACHHANG()
        {
            this.DATBANs = new HashSet<DATBAN>();
            this.TAIKHOANs = new HashSet<TAIKHOAN>();
        }
    
        public string MaKH { get; set; }
        public string HoTen { get; set; }
        public string SDT { get; set; }
        public string LoaiKH { get; set; }
        public Nullable<int> DiemTichLuy { get; set; }
    
        public virtual ICollection<DATBAN> DATBANs { get; set; }
        public virtual ICollection<TAIKHOAN> TAIKHOANs { get; set; }
    }
}
