//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_LTW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        public NHANVIEN()
        {
            this.HOADONs = new HashSet<HOADON>();
            this.TAIKHOANs = new HashSet<TAIKHOAN>();
            this.PHIEUNHAPKHOes = new HashSet<PHIEUNHAPKHO>();
        }
    
        public string MaNV { get; set; }
        public string HoTen { get; set; }
        public string VaiTro { get; set; }
        public Nullable<int> Luong { get; set; }
    
        public virtual ICollection<HOADON> HOADONs { get; set; }
        public virtual ICollection<TAIKHOAN> TAIKHOANs { get; set; }
        public virtual ICollection<PHIEUNHAPKHO> PHIEUNHAPKHOes { get; set; }
    }
}
