//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_LTW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANAN
    {
        public BANAN()
        {
            this.DATBANs = new HashSet<DATBAN>();
        }
    
        public string MaBan { get; set; }
        public string TenBan { get; set; }
        public Nullable<int> SucChua { get; set; }
        public string TrangThai { get; set; }
    
        public virtual ICollection<DATBAN> DATBANs { get; set; }
    }
}
