//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_LTW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        public HOADON()
        {
            this.CHITIETHOADONs = new HashSet<CHITIETHOADON>();
        }
    
        public string MaHD { get; set; }
        public string MaDatBan { get; set; }
        public string MaNV { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public Nullable<int> TongTien { get; set; }
        public string PhuongThucTT { get; set; }
    
        public virtual ICollection<CHITIETHOADON> CHITIETHOADONs { get; set; }
        public virtual DATBAN DATBAN { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
