//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_LTW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MONAN
    {
        public MONAN()
        {
            this.CHITIETHOADONs = new HashSet<CHITIETHOADON>();
            this.MONAN_NGUYENLIEU = new HashSet<MONAN_NGUYENLIEU>();
        }
    
        public string MaMon { get; set; }
        public string TenMon { get; set; }
        public Nullable<int> Gia { get; set; }
        public string DonViTinh { get; set; }
        public string TrangThai { get; set; }
        public string MaLoai { get; set; }
        public string MoTa { get; set; }
        public string HinhAnh { get; set; }
    
        public virtual ICollection<CHITIETHOADON> CHITIETHOADONs { get; set; }
        public virtual LOAIMON LOAIMON { get; set; }
        public virtual ICollection<MONAN_NGUYENLIEU> MONAN_NGUYENLIEU { get; set; }
    }
}
