//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_LTW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGUYENLIEU
    {
        public NGUYENLIEU()
        {
            this.CHITIET_NHAPKHO = new HashSet<CHITIET_NHAPKHO>();
            this.MONAN_NGUYENLIEU = new HashSet<MONAN_NGUYENLIEU>();
        }
    
        public string MaNL { get; set; }
        public string TenNL { get; set; }
        public string DonViTinh { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
        public Nullable<int> MucCanhBao { get; set; }
    
        public virtual ICollection<CHITIET_NHAPKHO> CHITIET_NHAPKHO { get; set; }
        public virtual ICollection<MONAN_NGUYENLIEU> MONAN_NGUYENLIEU { get; set; }
    }
}
