//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_LTW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUNHAPKHO
    {
        public PHIEUNHAPKHO()
        {
            this.CHITIET_NHAPKHO = new HashSet<CHITIET_NHAPKHO>();
        }
    
        public string MaPN { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public string MaNV { get; set; }
    
        public virtual ICollection<CHITIET_NHAPKHO> CHITIET_NHAPKHO { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
